language: node_js
node_js:
  - '10.11.0'
dist: trusty

cache:
  directories:
    - 'node_modules'

before_script:
  - yarn lint:dry-run

script:
  - yarn build

deploy:
  provider: pages
  target-branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard.
  on:
    branch: master
  local_dir: dist/www/
